### ISSUE TITLE
The search function doesn't work in Safari and Firefox

### ISSUE THREAD

**Issue by P4R** [jtebert/jekyll-polymer#2]
The search function doesn't show any results in Safari and Firefox.
I try demo page of search plugin and it works in all browser.
Demo: http://christian.fei.ninja/Simple-Jekyll-Search/

**Comment by P4R** [comment]
@jtebert
 Why did you close this issue? It's not solved.

**Comment by jtebert** [comment]
I thought that's what you fixed with your pull request. I'm not having this issue. I'll look into it further. Are you getting any errors in the console?

**Comment by jtebert** [comment]
OK, the issue seems to be that the script in the `my-search-bar` template isn't getting run when loaded. My guess is that this is an issue with the way Safari/Firefox handle scripts inside of web components. As a kludgy fix, you could move that script outside of the component, but I'm looking for a better workaround.

**Comment by P4R** [comment]
I move the script to default layout, I think that it's the better place. Here is the PR #3

**Comment by jtebert** [comment]
I think it's better (maintaining modularity) to have all the scripts within the component. Loading simple-jekyll-search and running the setup now all happens within the component, with my modifications.

**Comment by P4R** [comment]
:thumbsup:
